# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings 
title: Banyan Logic
email: srinikasturi@banyanlogic.com
description: > # this means to ignore newlines until "baseurl:"
 Banyan Logic is a cybersecurity firm headquartered in Reston, VA, USA. We provide Cyber Security training, process automation, and auditing.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
bg: 'bg.jpg'
logo: 'bg.jpg'
# Build settings
markdown: kramdown
permalink: /:categories/:title/
# Adding new theme
theme: jekyll-theme-leap-day

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

# Srini K edits starting d270818 
#collections:
#  trainingpages:
#    output: true
#	permalink: /trainingpages/:path/
